### ISSUE TITLE
Add a method to change the "baseRoute" on the fly

### ISSUE THREAD

**Issue by Vyperus** [process-engine/consumer_client#9]
#### Describe your issue

To add a "Configurations-Panel" in Charon I need a possibility to change the baseRoute while Charon is up and running.

See https://github.com/process-engine/charon/issues/86

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by heikomat** [comment]
This was implemented in #10
